#!/usr/bin/env python3
"""PreToolUse hook: block git commits that claim Claude authorship.

Claude Code appends attribution trailers ("Generated with Claude Code",
"Co-Authored-By: Claude", a claude.ai/code session link) to commits by
default. This repo's history should read as ordinary human commits, so this
hook inspects every Bash command before it runs and denies the ones that
would write such a trailer into a commit message.

`attribution.commit` in .claude/settings.json already switches the default
trailers off; this hook is the backstop for messages composed by hand or by
an agent that ignores the setting.

Reads the hook payload as JSON on stdin, writes a PreToolUse decision as
JSON on stdout. Stdlib only — no dependencies, no network.
"""

import json
import re
import sys
from pathlib import Path

# Only inspect commands that actually run `git commit` (`git -C dir commit`,
# `cd foo && git commit`, ... all match). Anything else passes straight
# through.
GIT_COMMIT = re.compile(r"\bgit\b[^\n;&|]*?\bcommit\b")

# Patterns that assert Claude wrote the commit. Deliberately narrow: a commit
# message is free to *mention* Claude (this repo has .claude/ config in it),
# it just may not claim Claude as the author.
ATTRIBUTION_PATTERNS = [
    (
        re.compile(r"co-authored-by:[^\n]*(claude|anthropic)", re.I),
        "Co-Authored-By trailer crediting Claude",
    ),
    (
        re.compile(
            r"\b(generated|written|authored|created|produced|made|committed|"
            r"implemented|assisted)\s+(with|by)\b[^\n]{0,30}\bclaude\b",
            re.I,
        ),
        "phrase claiming the change was generated by Claude",
    ),
    (
        re.compile(r"\bclaude[-\s]?(generated|authored|assisted|written)\b", re.I),
        "phrase claiming the change was generated by Claude",
    ),
    (
        re.compile(r"\[claude code\]", re.I),
        "Claude Code attribution link",
    ),
    (
        re.compile(r"claude\.ai/code", re.I),
        "claude.ai/code session link",
    ),
    (
        re.compile(r"^\s*claude-session:", re.I | re.M),
        "Claude-Session trailer",
    ),
]

# `git commit -F msg.txt` / `--file=msg.txt` keeps the message out of the
# command string, so pull those files in too.
MESSAGE_FILE_FLAGS = [
    re.compile(r"(?:^|\s)-F\s+(\S+)"),
    re.compile(r"(?:^|\s)--file[=\s]+(\S+)"),
]


def message_file_text(command: str) -> str:
    """Return the contents of any -F/--file message files named in `command`."""
    chunks = []
    for pattern in MESSAGE_FILE_FLAGS:
        for match in pattern.finditer(command):
            path = Path(match.group(1).strip("\"'"))
            try:
                chunks.append(path.read_text(encoding="utf-8", errors="replace"))
            except OSError:
                # Unreadable or not-yet-written path: nothing to inspect.
                continue
    return "\n".join(chunks)


def find_attribution(command: str):
    """Return (matched text, description) for the first attribution found."""
    haystack = command + "\n" + message_file_text(command)
    for pattern, description in ATTRIBUTION_PATTERNS:
        match = pattern.search(haystack)
        if match:
            return match.group(0).strip(), description
    return None


def deny(reason: str) -> None:
    json.dump(
        {
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "deny",
                "permissionDecisionReason": reason,
            }
        },
        sys.stdout,
    )


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, UnicodeDecodeError):
        # Malformed payload: stay out of the way rather than block real work.
        return 0

    if payload.get("tool_name") != "Bash":
        return 0

    command = payload.get("tool_input", {}).get("command") or ""
    if not GIT_COMMIT.search(command):
        return 0

    found = find_attribution(command)
    if not found:
        return 0

    matched, description = found
    deny(
        f"Commit message contains a {description} ({matched!r}). "
        "This repository does not credit Claude in commit messages — "
        "rewrite the message to describe the change only, with no "
        "Co-Authored-By: Claude trailer, no 'Generated with Claude Code' "
        "line, and no claude.ai session link."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
