#:schema node_modules/wrangler/config-schema.json

# Cloudflare Pages project configuration
# See: https://developers.cloudflare.com/pages/functions/wrangler-configuration/
name = "merger-tracker"
pages_build_output_dir = "merger-tracker/frontend/dist"
compatibility_date = "2024-09-23"
