"""Cloudflare Pages ``_redirects`` rules for retired party pages.

A party page disappears when its party is folded into a canonical group in
``related_parties.json`` — the merger it appeared on now links to the group's
page instead, and :mod:`static_data.prune` deletes the old file. Without a
redirect, every bookmark, citation and search result pointing at the old URL
lands on "Party not found".

This writes those redirects into ``merger-tracker/frontend/public/_redirects``
so Cloudflare answers them with a 301 at the edge, before the SPA loads. The
file is otherwise hand-maintained, so the generated rules live inside a marked
block and everything outside it is preserved verbatim.

Two static rules are written per retired id, covering both URL shapes the site
has ever produced::

    /parties/{id}            → /parties/{live_id}/{slug}
    /parties/{id}/{id}       → /parties/{live_id}/{slug}

The second is the canonical form for a synthesised party page, whose decorative
slug equals its id (see ``slug.party_path``).

Static rules, and static rules first
────────────────────────────────────
A ``_redirects`` file takes 2,000 static rules but only 100 *dynamic* ones —
those using a splat or a ``:placeholder``. Splats would let one rule cover a
retired id under any stale slug, but at ~250 retired ids that budget is gone
several times over, so every generated rule here is static.

The ordering is not cosmetic either. Cloudflare's docs say "static redirects
should appear before dynamic redirects", and when a dynamic rule leads the
file, rules past the 100th are reported to be dropped silently — no build
warning, no dashboard error, they simply never fire. So the generated block is
written *above* whatever hand-maintained rules the file already had (the
project's ``/matters/*`` splat among them), and :func:`_warn_on_rule_order`
flags any hand-written static rule left stranded below a dynamic one.

https://developers.cloudflare.com/pages/configuration/redirects/
"""

from pathlib import Path

from slug import party_path

BEGIN_MARKER = "# BEGIN generated party redirects"
END_MARKER = "# END generated party redirects"

_BLOCK_HEADER = [
    BEGIN_MARKER,
    "# Party pages retired by a fold-in into a canonical group, or by a party",
    "# the ACCC renamed. Generated by scripts/static_data/outputs/redirects.py",
    "# from related_parties.json + data/processed/party_redirects.json.",
    "# Do not edit by hand — regenerate with scripts/generate_static_data.py.",
    "#",
    "# These are all static rules and must stay ABOVE any splat/:placeholder",
    "# rule: Cloudflare wants static redirects first, and rules past the 100th",
    "# can be dropped silently when a dynamic rule leads the file.",
]


def build_rules(aliases: dict, pages: list) -> list:
    """Render ``{retired_id: live_id}`` into ``_redirects`` lines.

    ``pages`` supplies each live page's canonical name so the target carries
    its readable slug. Two kinds of entry are dropped: one whose target has no
    page (redirecting to a URL that 404s is worse than the 404 we started
    with), and one whose *source* is itself a live page — a real page always
    wins, and a rule shadowing it would make that page unreachable.
    """
    names = {p['id']: p.get('canonical_name') or '' for p in pages}

    lines = []
    for retired_id, live_id in sorted(aliases.items()):
        if live_id not in names or retired_id == live_id or retired_id in names:
            continue
        target = party_path(live_id, names[live_id])
        lines.append(f"/parties/{retired_id}  {target}  301")
        lines.append(f"/parties/{retired_id}/{retired_id}  {target}  301")
    return lines


def _strip_existing_block(text: str) -> str:
    """Return ``text`` with any previously generated block removed.

    Blank lines left where the block was are trimmed off both ends, so writing
    the file repeatedly does not accumulate whitespace around what it preserves.
    """
    kept, skipping = [], False
    for line in text.splitlines():
        if line.strip() == BEGIN_MARKER:
            skipping = True
            continue
        if line.strip() == END_MARKER:
            skipping = False
            continue
        if not skipping:
            kept.append(line)
    return "\n".join(kept).strip("\n")


def is_dynamic(line: str) -> bool:
    """Does this rule line use a splat or a ``:placeholder``?

    Those come out of the 100-rule dynamic budget rather than the 2,000-rule
    static one, and must sort below every static rule.
    """
    parts = line.split()
    if len(parts) < 2 or not parts[0].startswith('/'):
        return False
    source = parts[0]
    return '*' in source or ':' in source


def _warn_on_rule_order(preserved: str) -> None:
    """Warn when a hand-written static rule sits below a dynamic one.

    The generated block goes above everything, so it is safe by construction —
    but a hand-written static rule stranded under a splat is at risk of being
    silently dropped, and that failure is invisible at deploy time.
    """
    seen_dynamic = None
    for line in preserved.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith('#'):
            continue
        if is_dynamic(stripped):
            seen_dynamic = stripped.split()[0]
        elif seen_dynamic:
            print(
                f"  WARNING: static redirect '{stripped.split()[0]}' appears below dynamic "
                f"rule '{seen_dynamic}' in _redirects. Cloudflare wants static rules first; "
                f"rules after a leading dynamic rule can be dropped silently."
            )
            return


def generate(aliases: dict, pages: list, redirects_path: Path) -> int:
    """Write the generated block into ``_redirects``. Returns the rule count.

    Hand-written rules in the file are kept as they are; the generated block is
    replaced wholesale and placed *above* them, because every generated rule is
    static and Cloudflare wants static rules ahead of dynamic ones. Nothing is
    written when there are no rules and no block already exists, so a project
    with no retired pages keeps a clean file.
    """
    redirects_path = Path(redirects_path)
    existing = redirects_path.read_text(encoding='utf-8') if redirects_path.exists() else ""
    preserved = _strip_existing_block(existing)

    rules = build_rules(aliases, pages)
    if not rules:
        if preserved != existing.rstrip("\n"):
            redirects_path.write_text(preserved + "\n", encoding='utf-8')
        return 0

    _warn_on_rule_order(preserved)

    parts = ["\n".join(_BLOCK_HEADER + rules + [END_MARKER])]
    if preserved:
        parts.append(preserved)
    redirects_path.parent.mkdir(parents=True, exist_ok=True)
    redirects_path.write_text("\n\n".join(parts) + "\n", encoding='utf-8')

    return len(rules)
