"""Cloudflare Pages ``_redirects`` rules for retired party pages.

A party page disappears when its party is folded into a canonical group in
``related_parties.json`` — the merger it appeared on now links to the group's
page instead, and :mod:`static_data.prune` deletes the old file. Without a
redirect, every bookmark, citation and search result pointing at the old URL
lands on "Party not found".

This writes those redirects into ``merger-tracker/frontend/public/_redirects``
so Cloudflare answers them with a 301 at the edge, before the SPA loads. The
file is otherwise hand-maintained, so the generated rules live inside a marked
block and everything outside it is preserved verbatim.

Two static rules are written per retired id, covering both URL shapes the site
has ever produced::

    /parties/{id}            → /parties/{live_id}/{slug}
    /parties/{id}/{id}       → /parties/{live_id}/{slug}

The second is the canonical form for a synthesised party page, whose decorative
slug equals its id (see ``slug.party_path``). Splat rules would cover any stale
slug, but Cloudflare processes only 100 dynamic rules per project against 2,000
static ones, so static rules are what scale here.
"""

from pathlib import Path

from slug import party_path

BEGIN_MARKER = "# BEGIN generated party redirects"
END_MARKER = "# END generated party redirects"

_BLOCK_HEADER = [
    BEGIN_MARKER,
    "# Party pages retired by a fold-in into a canonical group, or by a party",
    "# the ACCC renamed. Generated by scripts/static_data/outputs/redirects.py",
    "# from related_parties.json + data/processed/party_redirects.json.",
    "# Do not edit by hand — regenerate with scripts/generate_static_data.py.",
]


def build_rules(aliases: dict, pages: list) -> list:
    """Render ``{retired_id: live_id}`` into ``_redirects`` lines.

    ``pages`` supplies each live page's canonical name so the target carries
    its readable slug. Two kinds of entry are dropped: one whose target has no
    page (redirecting to a URL that 404s is worse than the 404 we started
    with), and one whose *source* is itself a live page — a real page always
    wins, and a rule shadowing it would make that page unreachable.
    """
    names = {p['id']: p.get('canonical_name') or '' for p in pages}

    lines = []
    for retired_id, live_id in sorted(aliases.items()):
        if live_id not in names or retired_id == live_id or retired_id in names:
            continue
        target = party_path(live_id, names[live_id])
        lines.append(f"/parties/{retired_id}  {target}  301")
        lines.append(f"/parties/{retired_id}/{retired_id}  {target}  301")
    return lines


def _strip_existing_block(text: str) -> str:
    """Return ``text`` with any previously generated block removed."""
    kept, skipping = [], False
    for line in text.splitlines():
        if line.strip() == BEGIN_MARKER:
            skipping = True
            continue
        if line.strip() == END_MARKER:
            skipping = False
            continue
        if not skipping:
            kept.append(line)
    return "\n".join(kept).rstrip("\n")


def generate(aliases: dict, pages: list, redirects_path: Path) -> int:
    """Write the generated block into ``_redirects``. Returns the rule count.

    Hand-written rules in the file are kept as they are; the generated block is
    replaced wholesale. Nothing is written when there are no rules and no block
    already exists, so a project with no retired pages keeps a clean file.
    """
    redirects_path = Path(redirects_path)
    existing = redirects_path.read_text(encoding='utf-8') if redirects_path.exists() else ""
    preserved = _strip_existing_block(existing)

    rules = build_rules(aliases, pages)
    if not rules:
        if preserved != existing.rstrip("\n"):
            redirects_path.write_text(preserved + "\n", encoding='utf-8')
        return 0

    parts = [preserved] if preserved else []
    parts.append("\n".join(_BLOCK_HEADER + rules + [END_MARKER]))
    redirects_path.parent.mkdir(parents=True, exist_ok=True)
    redirects_path.write_text("\n\n".join(parts) + "\n", encoding='utf-8')

    return len(rules)
