import { useParams, Link } from 'react-router-dom';
import { FaChevronLeft } from 'react-icons/fa';
import LoadingSpinner from '../components/LoadingSpinner';
import ErrorCard from '../components/ErrorCard';
import IndustryMergerGroups from '../components/IndustryMergerGroups';
import SEO from '../components/SEO';
import { API_ENDPOINTS } from '../config';
import { useFetchData } from '../hooks/useFetchData';

function IndustryDetail() {
  const { code } = useParams();
  let decodedCode;
  try {
    decodedCode = decodeURIComponent(code);
  } catch {
    decodedCode = code;
  }

  const { data, loading, error } = useFetchData(
    API_ENDPOINTS.industryDetail(decodedCode),
    { cacheKey: `industry-${decodedCode}` }
  );
  // The industries list is used solely to resolve the display name. A failure
  // there shouldn't block the page — we fall back to the code.
  const { data: industriesData } = useFetchData(API_ENDPOINTS.industries, {
    cacheKey: 'industries-list',
  });
  const industries = industriesData?.industries || null;

  const isNotFound = error === 'HTTP 404';

  if (loading) return <LoadingSpinner />;

  if (error) {
    return (
      <ErrorCard
        title={isNotFound ? 'Industry not found' : 'Error loading industry'}
        message={isNotFound
          ? `We couldn't find an industry with code "${decodedCode}".`
          : error
        }
        backTo="/industries"
        backLabel="Back to industries"
      />
    );
  }

  if (!data) return null;

  const industryName = industries
    ? industries.find((i) => i.code === decodedCode)?.name || decodedCode
    : decodedCode;

  const mergers = data.mergers || [];

  // Per-industry stat breakdown (generated by the data pipeline). Fall back to
  // deriving the counts from the merger list if an older payload is cached.
  const phase2Count = data.phase_2_count ?? mergers.filter((m) => m.phase === 'Phase 2').length;
  const waiverCount = data.waiver_count ?? mergers.filter((m) => m.is_waiver).length;
  const activeCount = data.active_count ?? mergers.filter(
    (m) => m.status === 'Under assessment' || m.status === 'Assessment suspended'
  ).length;

  // Phase 1 duration stats, mirroring the dashboard. May be absent when the
  // industry has no completed Phase 1 reviews (e.g. waivers only).
  const duration = data.phase_duration;
  const avgDuration = duration?.average_business_days != null
    ? `${Math.round(duration.average_business_days)} business days`
    : 'N/A';
  const avgDurationSub = duration?.average_days != null
    ? `${Math.round(duration.average_days)} calendar days`
    : null;
  const medianDuration = duration?.median_business_days != null
    ? `${duration.median_business_days} business days`
    : 'N/A';
  const medianDurationSub = duration?.median_days != null
    ? `${duration.median_days} calendar days`
    : null;

  const statCards = [
    { label: 'Total reviews', value: mergers.length },
    { label: 'Phase 2 reviews', value: phase2Count },
    { label: 'Waivers', value: waiverCount },
    { label: 'Under assessment', value: activeCount },
    { label: 'Avg phase 1 duration', value: avgDuration, subtitle: avgDurationSub },
    { label: 'Median phase 1 duration', value: medianDuration, subtitle: medianDurationSub },
  ];

  return (
    <>
      <SEO
        title={industryName}
        description={`${mergers.length} merger${mergers.length !== 1 ? 's' : ''} in the ${industryName} industry reviewed by the ACCC.`}
        url={`/industries/${encodeURIComponent(decodedCode)}`}
      />
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8 animate-fade-in">
        <Link
          to="/industries"
          className="inline-flex items-center gap-1.5 text-sm text-gray-500 hover:text-primary mb-5 transition-colors"
        >
          <FaChevronLeft className="w-4 h-4" aria-hidden="true" />
          Back to industries
        </Link>

        <div className="bg-white rounded-2xl border border-gray-100 shadow-card p-6 mb-6 card-accent">
          <div className="pt-1">
            <h1 className="text-2xl font-bold text-gray-900 tracking-tight">
              {industryName}
            </h1>
            <p className="text-sm text-gray-500 mt-1">
              ANZSIC code: {decodedCode} · {mergers.length} merger{mergers.length !== 1 ? 's' : ''}
            </p>
          </div>
        </div>

        {mergers.length > 0 && (
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 mb-6">
            {statCards.map(({ label, value, subtitle }) => (
              <div key={label} className="bg-white p-5 rounded-2xl border border-gray-100 shadow-card">
                <p className="text-xs font-medium text-gray-500 uppercase tracking-wider">{label}</p>
                <p className="text-2xl font-bold text-gray-900 mt-1.5 tracking-tight tabular-nums">
                  {value}
                </p>
                {subtitle && (
                  <p className="text-xs text-gray-500 mt-1">{subtitle}</p>
                )}
              </div>
            ))}
          </div>
        )}

        <IndustryMergerGroups mergers={mergers} variant="full" />

        {mergers.length === 0 && (
          <div className="text-center py-16">
            <p className="text-gray-500 font-medium">No mergers found for this industry</p>
          </div>
        )}
      </div>
    </>
  );
}

export default IndustryDetail;
