import { useState, useMemo } from 'react';
import { Link } from 'react-router-dom';
import { FaChevronRight } from 'react-icons/fa';
import LoadingSpinner from '../components/LoadingSpinner';
import ErrorCard from '../components/ErrorCard';
import IndustryMergerGroups from '../components/IndustryMergerGroups';
import PhaseDurationComparison from '../components/PhaseDurationComparison';
import SearchInput from '../components/SearchInput';
import SEO from '../components/SEO';
import TrackButton from '../components/TrackButton';
import Breadcrumb from '../components/Breadcrumb';
import DetailStatGrid from '../components/DetailStatGrid';
import { API_ENDPOINTS } from '../config';
import { useFetchData } from '../hooks/useFetchData';
import { useDecodedParam } from '../hooks/useDecodedParam';
import { useTracking } from '../context/TrackingContext';
import { industryPath } from '../utils/slug';
import { MERGER_STATUS, PHASES } from '../constants/mergerStatus';
import { CARD, SECTION_HEADING } from '../utils/classNames';

// ANZSIC level → human label for the page subtitle and breadcrumb.
const LEVEL_LABELS = {
  division: 'Division',
  subdivision: 'Subdivision',
  group: 'Group',
  class: 'Class',
};

function IndustryDetail() {
  const decodedCode = useDecodedParam('code');

  const { data, loading, error } = useFetchData(
    API_ENDPOINTS.industryDetail(decodedCode),
    { cacheKey: `industry-${decodedCode}` }
  );
  // The industries list is only a fallback for the display name on older
  // payloads — the detail file now carries its own name. A failure here
  // shouldn't block the page.
  const { data: industriesData } = useFetchData(API_ENDPOINTS.industries, {
    cacheKey: 'industries-list',
  });
  const industries = industriesData?.industries || null;

  // Parent industry detail — fetched once the main payload reveals the parent
  // code, so we can compare Phase 1 durations against the next level up. The
  // hook pauses while the URL is falsy (no parent / not yet loaded). A failure
  // here is non-fatal: the comparison simply falls back to this industry alone.
  const parentCode = data?.parent?.code;
  const { data: parentData } = useFetchData(
    parentCode ? API_ENDPOINTS.industryDetail(parentCode) : null,
    parentCode ? { cacheKey: `industry-${parentCode}` } : {}
  );

  // Overall all-industries figures (shared cache with the dashboard). Fetched
  // for every level so each industry can be compared against the market as a
  // whole, not just against its immediate parent.
  const { data: statsData } = useFetchData(
    data ? API_ENDPOINTS.stats : null,
    data ? { cacheKey: 'dashboard-stats' } : {}
  );

  const { isIndustryTracked, toggleIndustryTracking } = useTracking();

  // Local free-text filter for the merger list on this page.
  const [mergerSearch, setMergerSearch] = useState('');

  const trimmedSearch = mergerSearch.trim().toLowerCase();
  const filteredMergers = useMemo(() => {
    const allMergers = data?.mergers || [];
    if (!trimmedSearch) return allMergers;
    return allMergers.filter((m) =>
      (m.merger_name || '').toLowerCase().includes(trimmedSearch) ||
      (m.status || '').toLowerCase().includes(trimmedSearch) ||
      (m.determination || '').toLowerCase().includes(trimmedSearch)
    );
  }, [data?.mergers, trimmedSearch]);

  const isNotFound = error === 'HTTP 404';

  if (loading) return <LoadingSpinner />;

  if (error) {
    return (
      <ErrorCard
        title={isNotFound ? 'Industry not found' : 'Error loading industry'}
        message={isNotFound
          ? `We couldn't find an industry with code "${decodedCode}".`
          : error
        }
        backTo="/industries"
        backLabel="Back to industries"
      />
    );
  }

  if (!data) return null;

  // Prefer the name baked into the detail file; fall back to the index, then code.
  const industryName = data.name
    || (industries ? industries.find((i) => i.code === decodedCode)?.name : null)
    || decodedCode;

  const following = isIndustryTracked(decodedCode);

  const levelLabel = data.level ? LEVEL_LABELS[data.level] : null;
  const ancestors = data.ancestors || [];
  const children = data.children || [];

  const mergers = data.mergers || [];

  // Per-industry stat breakdown (generated by the data pipeline). Fall back to
  // deriving the counts from the merger list if an older payload is cached.
  const phase2Count = data.phase_2_count ?? mergers.filter((m) => m.phase === PHASES.PHASE_2).length;
  const waiverCount = data.waiver_count ?? mergers.filter((m) => m.is_waiver).length;
  const activeCount = data.active_count ?? mergers.filter(
    (m) => m.status === MERGER_STATUS.UNDER_ASSESSMENT || m.status === MERGER_STATUS.ASSESSMENT_SUSPENDED
  ).length;

  // Phase 1 duration stats, mirroring the dashboard. May be absent when the
  // industry has no completed Phase 1 reviews (e.g. waivers only). These are
  // surfaced visually via PhaseDurationComparison (vs the parent industry)
  // rather than as flat stat cards.
  const duration = data.phase_duration;
  // Baselines to compare this industry's durations against: its parent in the
  // ANZSIC hierarchy (when it has one) and the overall all-industries figures.
  // Divisions (no parent) show one baseline line; deeper levels show two.
  const comparisons = [];
  if (parentCode && parentData?.phase_duration) {
    comparisons.push({
      name: data.parent?.name || 'Parent industry',
      duration: parentData.phase_duration,
    });
  }
  if (statsData?.phase_duration) {
    comparisons.push({ name: 'All industries', duration: statsData.phase_duration });
  }

  // Waiver duration (notification → determination) with the same baselines,
  // shown as a second chart alongside Phase 1. Absent when the industry has no
  // completed waivers.
  const waiverDuration = data.waiver_duration;
  const waiverComparisons = [];
  if (parentCode && parentData?.waiver_duration) {
    waiverComparisons.push({
      name: data.parent?.name || 'Parent industry',
      duration: parentData.waiver_duration,
    });
  }
  if (statsData?.waiver_duration?.average_business_days != null) {
    waiverComparisons.push({ name: 'All industries', duration: statsData.waiver_duration });
  }

  const statCards = [
    { label: 'Total reviews', value: mergers.length },
    { label: 'Phase 2 reviews', value: phase2Count },
    { label: 'Waivers', value: waiverCount },
    { label: 'Under assessment', value: activeCount },
  ];

  return (
    <>
      <SEO
        title={industryName}
        description={`${mergers.length} merger${mergers.length !== 1 ? 's' : ''} in the ${industryName} industry${levelLabel ? ` (ANZSIC ${levelLabel.toLowerCase()} ${decodedCode})` : ''} reviewed by the ACCC.`}
        url={industryPath(decodedCode, industryName)}
      />
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8 animate-fade-in">
        {/* Breadcrumb: Industries → division → … → current node */}
        <Breadcrumb
          ariaLabel="Industry hierarchy"
          items={[
            { label: 'Industries', to: '/industries' },
            ...ancestors.map((a) => ({ label: a.name, to: industryPath(a.code, a.name) })),
            { label: industryName },
          ]}
        />

        <div className={`${CARD} p-6 mb-6 card-accent`}>
          <div className="pt-1 flex items-start justify-between gap-4">
            <div>
              <h1 className="text-2xl font-bold text-gray-900 tracking-tight">
                {industryName}
              </h1>
              <p className="text-sm text-gray-500 mt-1">
                ANZSIC {levelLabel ? `${levelLabel.toLowerCase()} ` : 'code: '}{decodedCode} · {mergers.length} merger{mergers.length !== 1 ? 's' : ''}
              </p>
            </div>
            <TrackButton
              active={following}
              onClick={() => toggleIndustryTracking(decodedCode, industryName)}
              activeLabel="Following"
              inactiveLabel="Follow"
              activeAriaLabel="Stop following this industry"
              inactiveAriaLabel="Follow this industry for new filings and determinations"
              title="Get notified when a new merger is filed or a determination is published in this industry"
            />
          </div>
        </div>

        {mergers.length > 0 && <DetailStatGrid statCards={statCards} />}

        {/* Phase 1 duration, shown visually against the parent industry. */}
        {mergers.length > 0 && duration?.average_business_days != null && (
          <div className="mb-6">
            <PhaseDurationComparison
              duration={duration}
              comparisons={comparisons}
            />
          </div>
        )}

        {/* Waiver duration, shown the same way for industries with waivers. */}
        {mergers.length > 0 && waiverDuration?.average_business_days != null && (
          <div className="mb-6">
            <PhaseDurationComparison
              title="Waiver duration"
              duration={waiverDuration}
              comparisons={waiverComparisons}
            />
          </div>
        )}

        {/* Sub-industries: children one level down, for drilling into the tree. */}
        {children.length > 0 && (
          <div className={`${CARD} p-6 mb-6`}>
            <h2 className={`${SECTION_HEADING} mb-3`}>
              Sub-industries
            </h2>
            <ul className="divide-y divide-gray-50">
              {children.map((child) => (
                <li key={child.code}>
                  <Link
                    to={industryPath(child.code, child.name)}
                    className="flex items-center justify-between gap-3 py-2.5 group"
                  >
                    <span className="text-sm text-gray-900 group-hover:text-primary transition-colors">
                      <span className="text-gray-500 tabular-nums mr-2">{child.code}</span>
                      {child.name}
                    </span>
                    <span className="flex items-center gap-2 shrink-0">
                      <span className="inline-flex items-center justify-center min-w-[2.25rem] px-2.5 py-1 rounded-lg text-xs font-semibold bg-primary/10 text-primary tabular-nums">
                        {child.merger_count ?? 0}
                      </span>
                      <FaChevronRight className="w-3 h-3 text-gray-300 group-hover:text-primary transition-colors" aria-hidden="true" />
                    </span>
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        )}

        {mergers.length > 0 && (
          <div className="flex flex-wrap items-center justify-between gap-x-3 gap-y-1 mb-3">
            <h2 className={SECTION_HEADING}>
              Mergers in this industry
            </h2>
            {mergers.length > 5 && (
              <p className={`${SECTION_HEADING} shrink-0`}>
                Showing {filteredMergers.length} of {mergers.length}
              </p>
            )}
          </div>
        )}

        {/* Free-text filter for the merger list, worth showing only once the
            list is long enough to be awkward to scan by eye. */}
        {mergers.length > 5 && (
          <SearchInput
            ariaLabel="Search mergers in this industry"
            placeholder="Search mergers in this industry..."
            value={mergerSearch}
            onChange={(e) => setMergerSearch(e.target.value)}
            className="mb-4"
          />
        )}

        <IndustryMergerGroups mergers={filteredMergers} variant="full" />

        {mergers.length > 0 && filteredMergers.length === 0 && (
          <div className="text-center py-12">
            <p className="text-gray-500 font-medium">No mergers match &ldquo;{mergerSearch.trim()}&rdquo;</p>
          </div>
        )}

        {mergers.length === 0 && (
          <div className="text-center py-16">
            <p className="text-gray-500 font-medium">No mergers found for this industry</p>
            {children.length > 0 && (
              <p className="text-gray-500 text-sm mt-1">
                Browse the sub-industries above to find merger activity.
              </p>
            )}
          </div>
        )}
      </div>
    </>
  );
}

export default IndustryDetail;
