import { useState, useMemo } from 'react';
import { useParams, Link } from 'react-router-dom';
import { FaChevronRight } from 'react-icons/fa';
import LoadingSpinner from '../components/LoadingSpinner';
import ErrorCard from '../components/ErrorCard';
import IndustryMergerGroups from '../components/IndustryMergerGroups';
import PhaseDurationComparison from '../components/PhaseDurationComparison';
import SEO from '../components/SEO';
import { API_ENDPOINTS } from '../config';
import { useFetchData } from '../hooks/useFetchData';

// ANZSIC level → human label for the page subtitle and breadcrumb.
const LEVEL_LABELS = {
  division: 'Division',
  subdivision: 'Subdivision',
  group: 'Group',
  class: 'Class',
};

function IndustryDetail() {
  const { code } = useParams();
  let decodedCode;
  try {
    decodedCode = decodeURIComponent(code);
  } catch {
    decodedCode = code;
  }

  const { data, loading, error } = useFetchData(
    API_ENDPOINTS.industryDetail(decodedCode),
    { cacheKey: `industry-${decodedCode}` }
  );
  // The industries list is only a fallback for the display name on older
  // payloads — the detail file now carries its own name. A failure here
  // shouldn't block the page.
  const { data: industriesData } = useFetchData(API_ENDPOINTS.industries, {
    cacheKey: 'industries-list',
  });
  const industries = industriesData?.industries || null;

  // Parent industry detail — fetched once the main payload reveals the parent
  // code, so we can compare Phase 1 durations against the next level up. The
  // hook pauses while the URL is falsy (no parent / not yet loaded). A failure
  // here is non-fatal: the comparison simply falls back to this industry alone.
  const parentCode = data?.parent?.code;
  const { data: parentData } = useFetchData(
    parentCode ? API_ENDPOINTS.industryDetail(parentCode) : null,
    parentCode ? { cacheKey: `industry-${parentCode}` } : {}
  );

  // Overall all-industries figures (shared cache with the dashboard). Fetched
  // for every level so each industry can be compared against the market as a
  // whole, not just against its immediate parent.
  const { data: statsData } = useFetchData(
    data ? API_ENDPOINTS.stats : null,
    data ? { cacheKey: 'dashboard-stats' } : {}
  );

  // Local free-text filter for the merger list on this page.
  const [mergerSearch, setMergerSearch] = useState('');

  const allMergers = data?.mergers || [];
  const trimmedSearch = mergerSearch.trim().toLowerCase();
  const filteredMergers = useMemo(() => {
    if (!trimmedSearch) return allMergers;
    return allMergers.filter((m) =>
      (m.merger_name || '').toLowerCase().includes(trimmedSearch) ||
      (m.status || '').toLowerCase().includes(trimmedSearch)
    );
  }, [allMergers, trimmedSearch]);

  const isNotFound = error === 'HTTP 404';

  if (loading) return <LoadingSpinner />;

  if (error) {
    return (
      <ErrorCard
        title={isNotFound ? 'Industry not found' : 'Error loading industry'}
        message={isNotFound
          ? `We couldn't find an industry with code "${decodedCode}".`
          : error
        }
        backTo="/industries"
        backLabel="Back to industries"
      />
    );
  }

  if (!data) return null;

  // Prefer the name baked into the detail file; fall back to the index, then code.
  const industryName = data.name
    || (industries ? industries.find((i) => i.code === decodedCode)?.name : null)
    || decodedCode;

  const levelLabel = data.level ? LEVEL_LABELS[data.level] : null;
  const ancestors = data.ancestors || [];
  const children = data.children || [];

  const mergers = data.mergers || [];

  // Per-industry stat breakdown (generated by the data pipeline). Fall back to
  // deriving the counts from the merger list if an older payload is cached.
  const phase2Count = data.phase_2_count ?? mergers.filter((m) => m.phase === 'Phase 2').length;
  const waiverCount = data.waiver_count ?? mergers.filter((m) => m.is_waiver).length;
  const activeCount = data.active_count ?? mergers.filter(
    (m) => m.status === 'Under assessment' || m.status === 'Assessment suspended'
  ).length;

  // Phase 1 duration stats, mirroring the dashboard. May be absent when the
  // industry has no completed Phase 1 reviews (e.g. waivers only). These are
  // surfaced visually via PhaseDurationComparison (vs the parent industry)
  // rather than as flat stat cards.
  const duration = data.phase_duration;
  // Baselines to compare this industry's durations against: its parent in the
  // ANZSIC hierarchy (when it has one) and the overall all-industries figures.
  // Divisions (no parent) show one baseline line; deeper levels show two.
  const comparisons = [];
  if (parentCode && parentData?.phase_duration) {
    comparisons.push({
      name: data.parent?.name || 'Parent industry',
      duration: parentData.phase_duration,
    });
  }
  if (statsData?.phase_duration) {
    comparisons.push({ name: 'All industries', duration: statsData.phase_duration });
  }

  const statCards = [
    { label: 'Total reviews', value: mergers.length },
    { label: 'Phase 2 reviews', value: phase2Count },
    { label: 'Waivers', value: waiverCount },
    { label: 'Under assessment', value: activeCount },
  ];

  return (
    <>
      <SEO
        title={industryName}
        description={`${mergers.length} merger${mergers.length !== 1 ? 's' : ''} in the ${industryName} industry${levelLabel ? ` (ANZSIC ${levelLabel.toLowerCase()} ${decodedCode})` : ''} reviewed by the ACCC.`}
        url={`/industries/${encodeURIComponent(decodedCode)}`}
      />
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8 animate-fade-in">
        {/* Breadcrumb: Industries → division → … → current node */}
        <nav aria-label="Industry hierarchy" className="mb-5">
          <ol className="flex flex-wrap items-center gap-x-1.5 gap-y-1 text-sm text-gray-500">
            <li>
              <Link to="/industries" className="hover:text-primary transition-colors">
                Industries
              </Link>
            </li>
            {ancestors.map((a) => (
              <li key={a.code} className="flex items-center gap-x-1.5">
                <FaChevronRight className="w-3 h-3 text-gray-300" aria-hidden="true" />
                <Link
                  to={`/industries/${encodeURIComponent(a.code)}`}
                  className="hover:text-primary transition-colors"
                >
                  {a.name}
                </Link>
              </li>
            ))}
            <li className="flex items-center gap-x-1.5" aria-current="page">
              <FaChevronRight className="w-3 h-3 text-gray-300" aria-hidden="true" />
              <span className="font-medium text-gray-700">{industryName}</span>
            </li>
          </ol>
        </nav>

        <div className="bg-white rounded-2xl border border-gray-100 shadow-card p-6 mb-6 card-accent">
          <div className="pt-1">
            <h1 className="text-2xl font-bold text-gray-900 tracking-tight">
              {industryName}
            </h1>
            <p className="text-sm text-gray-500 mt-1">
              ANZSIC {levelLabel ? `${levelLabel.toLowerCase()} ` : 'code: '}{decodedCode} · {mergers.length} merger{mergers.length !== 1 ? 's' : ''}
            </p>
          </div>
        </div>

        {mergers.length > 0 && (
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-6">
            {statCards.map(({ label, value, subtitle }) => (
              <div key={label} className="bg-white p-5 rounded-2xl border border-gray-100 shadow-card">
                <p className="text-xs font-medium text-gray-500 uppercase tracking-wider">{label}</p>
                <p className="text-2xl font-bold text-gray-900 mt-1.5 tracking-tight tabular-nums">
                  {value}
                </p>
                {subtitle && (
                  <p className="text-xs text-gray-500 mt-1">{subtitle}</p>
                )}
              </div>
            ))}
          </div>
        )}

        {/* Phase 1 duration, shown visually against the parent industry. */}
        {mergers.length > 0 && duration?.average_business_days != null && (
          <div className="mb-6">
            <PhaseDurationComparison
              duration={duration}
              comparisons={comparisons}
            />
          </div>
        )}

        {/* Sub-industries: children one level down, for drilling into the tree. */}
        {children.length > 0 && (
          <div className="bg-white rounded-2xl border border-gray-100 shadow-card p-6 mb-6">
            <h2 className="text-xs font-medium text-gray-500 uppercase tracking-wider mb-3">
              Sub-industries
            </h2>
            <ul className="divide-y divide-gray-50">
              {children.map((child) => (
                <li key={child.code}>
                  <Link
                    to={`/industries/${encodeURIComponent(child.code)}`}
                    className="flex items-center justify-between gap-3 py-2.5 group"
                  >
                    <span className="text-sm text-gray-900 group-hover:text-primary transition-colors">
                      <span className="text-gray-400 tabular-nums mr-2">{child.code}</span>
                      {child.name}
                    </span>
                    <span className="flex items-center gap-2 shrink-0">
                      <span className="inline-flex items-center justify-center min-w-[2.25rem] px-2.5 py-1 rounded-lg text-xs font-semibold bg-primary/10 text-primary tabular-nums">
                        {child.merger_count ?? 0}
                      </span>
                      <FaChevronRight className="w-3 h-3 text-gray-300 group-hover:text-primary transition-colors" aria-hidden="true" />
                    </span>
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        )}

        {mergers.length > 0 && (
          <div className="flex flex-wrap items-center justify-between gap-x-3 gap-y-1 mb-3">
            <h2 className="text-xs font-medium text-gray-500 uppercase tracking-wider">
              Mergers in this industry
            </h2>
            {mergers.length > 5 && (
              <p className="text-xs font-medium text-gray-500 uppercase tracking-wider shrink-0">
                Showing {filteredMergers.length} of {mergers.length}
              </p>
            )}
          </div>
        )}

        {/* Free-text filter for the merger list, worth showing only once the
            list is long enough to be awkward to scan by eye. */}
        {mergers.length > 5 && (
          <div className="relative mb-4">
            <svg className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-500" fill="none" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor" aria-hidden="true">
              <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
            </svg>
            <input
              type="text"
              aria-label="Search mergers in this industry"
              className="w-full pl-10 pr-3 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:ring-2 focus:ring-primary/20 focus:border-primary focus:bg-white transition-all"
              placeholder="Search mergers in this industry..."
              value={mergerSearch}
              onChange={(e) => setMergerSearch(e.target.value)}
            />
          </div>
        )}

        <IndustryMergerGroups mergers={filteredMergers} variant="full" />

        {mergers.length > 0 && filteredMergers.length === 0 && (
          <div className="text-center py-12">
            <p className="text-gray-500 font-medium">No mergers match &ldquo;{mergerSearch.trim()}&rdquo;</p>
          </div>
        )}

        {mergers.length === 0 && (
          <div className="text-center py-16">
            <p className="text-gray-500 font-medium">No mergers found for this industry</p>
            {children.length > 0 && (
              <p className="text-gray-500 text-sm mt-1">
                Browse the sub-industries above to find merger activity.
              </p>
            )}
          </div>
        )}
      </div>
    </>
  );
}

export default IndustryDetail;
