// API configuration for static JSON files
// These files are generated by generate_static_data.py and served from /data/

export const API_ENDPOINTS = {
  mergers: '/data/mergers.json',
  stats: '/data/stats.json',
  timeline: '/data/timeline.json',
  industries: '/data/industries.json',
  upcomingEvents: '/data/upcoming-events.json',
};
