// API configuration for static JSON files
// These files are generated by generate_static_data.py and served from /data/

export const API_ENDPOINTS = {
  mergersListPage: (page) => `/data/mergers/list-page-${page}.json`,  // Paginated merger list
  mergersListMeta: '/data/mergers/list-meta.json',  // Pagination metadata for mergers list
  mergerDetail: (id) => `/data/mergers/${id}.json`,  // Individual merger file
  stats: '/data/stats.json',
  timelinePage: (page) => `/data/timeline-page-${page}.json`,  // Paginated timeline
  timelineMeta: '/data/timeline-meta.json',  // Pagination metadata for timeline
  industries: '/data/industries.json',
  industryDetail: (code) => `/data/industries/${code}.json`,  // Individual industry file with mergers
  upcomingEvents: '/data/upcoming-events.json',
  commentary: '/data/commentary.json',  // Mergers with user commentary
  digest: '/data/digest.json',  // Weekly digest of merger activity
};
