// API configuration for static JSON files
// These files are generated by generate_static_data.py and served from /data/

export const API_ENDPOINTS = {
  mergers: '/data/mergers.json',  // Legacy: full mergers list (not currently used by frontend)
  mergersList: '/data/mergers/list.json',  // Lightweight merger list (no events/descriptions)
  mergerDetail: (id) => `/data/mergers/${id}.json`,  // Individual merger file
  stats: '/data/stats.json',
  timeline: '/data/timeline.json',
  industries: '/data/industries.json',
  upcomingEvents: '/data/upcoming-events.json',
  commentary: '/data/commentary.json',  // Mergers with user commentary
};
