import { PHASES } from '../constants/mergerStatus';

/**
 * Phase buckets shown on the industry pages, in display order (most ACCC
 * scrutiny first). Each merger in an industry detail file carries a `phase`
 * field generated by the data pipeline (scripts/static_data/outputs/industries.py).
 */
export const PHASE_GROUPS = [
  { key: PHASES.PHASE_2, label: 'Phase 2 – detailed assessment' },
  { key: PHASES.PHASE_1, label: 'Phase 1 – initial assessment' },
  { key: PHASES.WAIVER, label: 'Waivers' },
];

/**
 * Classify a merger summary into a phase bucket. Prefers the pipeline-provided
 * `phase` field, falling back to `is_waiver` for any stale cached payloads that
 * predate the field.
 */
export function mergerPhase(merger) {
  if (merger.phase) return merger.phase;
  return merger.is_waiver ? PHASES.WAIVER : PHASES.PHASE_1;
}

/**
 * Split a list of merger summaries into ordered phase groups, dropping empty
 * groups so callers can render subheadings without showing zero counts.
 */
export function groupMergersByPhase(mergers) {
  return PHASE_GROUPS
    .map(({ key, label }) => ({
      key,
      label,
      mergers: mergers.filter((m) => mergerPhase(m) === key),
    }))
    .filter((group) => group.mergers.length > 0);
}
