"""Tests for the .claude/hooks/check_commit_message.py PreToolUse hook.

The hook denies `git commit` commands whose message credits Claude as the
author. It lives outside `scripts/`, so it is loaded here by path.
"""

import importlib.util
import json
from pathlib import Path

import pytest

HOOK_PATH = (
    Path(__file__).resolve().parents[2] / ".claude" / "hooks" / "check_commit_message.py"
)

_spec = importlib.util.spec_from_file_location("check_commit_message", HOOK_PATH)
hook = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(hook)


def decision(command, tool_name="Bash", monkeypatch=None, capsys=None):
    """Run the hook's main() over a synthetic payload, return its JSON output."""
    payload = json.dumps({"tool_name": tool_name, "tool_input": {"command": command}})
    monkeypatch.setattr("sys.stdin", __import__("io").StringIO(payload))
    assert hook.main() == 0
    out = capsys.readouterr().out
    return json.loads(out) if out else None


BLOCKED = [
    'git commit -m "fix\n\nCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>"',
    'git commit -m "fix\n\nCo-authored-by: Claude <noreply@anthropic.com>"',
    'git commit -m "fix\n\n🤖 Generated with [Claude Code](https://claude.ai/code)"',
    'git commit -m "fix\n\nClaude-Session: https://claude.ai/code/session_01"',
    'git commit --amend -m "tidy up\n\nWritten by Claude."',
    'git commit -m "tidy up (claude-generated)"',
    'cd merger-tracker && git commit -am "x\n\nGenerated by Claude"',
    'git -C /repo commit -m "x\n\nAuthored by Claude Code"',
]

ALLOWED = [
    # Mentioning Claude Code is fine — only authorship claims are blocked, and
    # this repo carries .claude/ config that commits legitimately describe.
    'git commit -m "Add Claude Code hook rejecting attribution trailers"',
    'git commit -m "docs: document the .claude/settings.json attribution keys"',
    'git commit -m "extract: handle Phase 2 notices without a decision date"',
    "git status",
    "git log --grep=claude",
    'git log --format="%an" | grep -i claude',
    "git push -u origin main",
]


@pytest.mark.parametrize("command", BLOCKED)
def test_attribution_is_denied(command, monkeypatch, capsys):
    result = decision(command, monkeypatch=monkeypatch, capsys=capsys)
    assert result is not None, f"expected a deny decision for: {command}"
    assert result["hookSpecificOutput"]["permissionDecision"] == "deny"


@pytest.mark.parametrize("command", ALLOWED)
def test_clean_commands_pass_through(command, monkeypatch, capsys):
    assert decision(command, monkeypatch=monkeypatch, capsys=capsys) is None


def test_non_bash_tools_are_ignored(monkeypatch, capsys):
    assert (
        decision(
            'git commit -m "x\n\nGenerated with Claude Code"',
            tool_name="Write",
            monkeypatch=monkeypatch,
            capsys=capsys,
        )
        is None
    )


def test_message_file_contents_are_inspected(tmp_path, monkeypatch, capsys):
    msg = tmp_path / "COMMIT_MSG"
    msg.write_text(
        "refactor: split the extractor\n\n"
        "Co-Authored-By: Claude <noreply@anthropic.com>\n",
        encoding="utf-8",
    )
    result = decision(
        f"git commit -F {msg}", monkeypatch=monkeypatch, capsys=capsys
    )
    assert result is not None
    assert result["hookSpecificOutput"]["permissionDecision"] == "deny"


def test_missing_message_file_does_not_crash(monkeypatch, capsys):
    assert (
        decision(
            "git commit -F /nonexistent/COMMIT_MSG",
            monkeypatch=monkeypatch,
            capsys=capsys,
        )
        is None
    )


def test_malformed_payload_is_ignored(monkeypatch, capsys):
    monkeypatch.setattr("sys.stdin", __import__("io").StringIO("not json"))
    assert hook.main() == 0
    assert capsys.readouterr().out == ""
